### ISSUE TITLE
Change query based on results of mutation

### ISSUE THREAD

**Issue by ckimes89** [ckimes89/graphql-net#40]
#39 made me realize that right now, there's no way to pass information from a mutation to the query that is run after a mutation. This should change so that we can support mutations that add a new entity and then immediately return that entity, or maybe return different values based on whether the mutation executed successfully or failed.

Example syntax:

```csharp
schema.AddMutation("addUser",
    new {
        name = string.Empty,                   
        active = false
    },
    (db, args) =>
    {
        var newUser = new User
        {
            Name = args.name,
            Active = args.active
        };
        db.Users.Add(newUser);
        db.SaveChanges();
        return newUser.Id;   // return information from the mutation
    },
    (db, args, id) => db.Users.FirstOrDefault(u => u.Id == id)
               // pass information to query as a third parameter
);
```

**Comment by benhysell** [comment]
+1
On, what would have been POST REST commands, one of the items I typically have to return is either the whole object, or at least the ID of the object I just created.

**Comment by ckimes89** [comment]
Returning values from mutations now works - and with no changes to the example syntax required!

I re-ordered the arguments to match the order of execution, that is the mutation function is now before the query function. However, I left the old overloads with an Obsolete attribute so they can still be used until the next version.
