### ISSUE TITLE
Quotes inside strings

### ISSUE THREAD

**Issue by fabiodr** [ckimes89/graphql-net#60]
Is there a way to escape single and double quotes inside strings?
The parser is throwing an error for strings with ' and "

I saw there is a treatment in the parser for especial chars but i don't read F# very well for digging into the issue.

**Comment by ckimes89** [comment]
According to the GraphQL spec, only double quotes are used for strings, so only double quotes need to be escaped:

https://facebook.github.io/graphql/#sec-Appendix-Grammar-Summary.Lexical-Tokens

However, there was a bug in the parser that wasn't handling those correctly. I've just fixed that and pushed to master.

Are you using the source directly, or referencing the NuGet project?

**Comment by ckimes89** [comment]
Either way, I just pushed an updated version (0.3.0) to NuGet with this fix. There are a few other changes along with it that might be breaking, but I tried to limit the API impact. Feel free to open another issue if you have issues upgrading.

**Comment by fabiodr** [comment]
I'm using from NuGet, i'll try this fix and look in github history for breaking changes then, thanks!!
