### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by MarianPalkus** [ckimes89/graphql-net#62]
Hi Chad,
i think about setting up a more detailled documentation similiar to [redux docs](http://redux.js.org/) which uses [gitbook](https://www.gitbook.com/).

Gitbook uses Markdown files which are stored in the git-repostiory (directory `docs`).

I tried it out on this fork: [https://github.com/MarianPalkus/graphql-net/](https://github.com/MarianPalkus/graphql-net/)

The gitbook looks like this: [https://www.gitbook.com/read/book/marianpalkus/graphql-net](https://www.gitbook.com/read/book/marianpalkus/graphql-net).

There are also some examples in the directory `examples` which are referenced in the docs.

What do you think of using gitbook? Do you think it is a good approach to store examples in the git-repo or should they live in their own git repo?

**Comment by ckimes89** [comment]
Hey Marian,

I really like the look of gitbook and I think it would be a great choice for the documentation. As for where the files should live, I'm happy with them sitting inside the existing repo. I think there's a lot of benefit to having everything living in one place.

The downside, of course, is that the commit history will get somewhat polluted with documentation commits vs. code commits. I'm not really worried about that right now, but if it becomes an issue we can always split it out later.
