### ISSUE TITLE
Add PostResolved functions

### ISSUE THREAD

**Issue by ckimes89** [ckimes89/graphql-net#7]
Better name pending, but the idea here is that some fields don't need to be executed against the database (and in many cases can't be). Since we don't need to build an `IQueryable` here, the resolver function definition can just be a `Func<>` instead of `Expression<Func>`. These resolver functions would be executed after the database query completes.

I'm not sure yet if we want to allow access to the data returned from the database in the resolver function, since I think it would necessarily have to be in `Dictionary<string, object>` form. Maaaybe we could offer some overload that lets you define parameters for the function in terms of an "args" anonymous object that is built from a member initializer expression and then tack that onto the query, but that's getting pretty complex. However, it would be better than Dictionary access, since you have no idea what will be populated in the dictionary.

The immediate use case for this is introspection, since the schema is in memory and not queryable from the database.

**Comment by PeteDuncanson** [comment]
Can you give me a usecase? Would this method allow you to calculate totals/taxes/etc. from values you did pull from the database, is that the idea?

Been happily reading you commits the last week or two in my inbox and keen to know more about how its all coming together. So far I like your thinking and the ease of reading of the code needed to implement a custom working solution within a project. :)

**Comment by ckimes89** [comment]
Hi Pete! I'm glad to hear the project is gaining some interest.

There are two main goals for this, one of which I think is more important than the other. The first is to have the ability to add a field that resolves based on something in memory, rather than from the database. As a contrived example, let's look at adding a `processName` field to the `User` type:

```
schema.AddType<User>
    .AddField(u => u.Id)
    .AddField(u => u.Name)
    .AddPostField("processName", () => Process.GetCurrentProcess().ProcessName);
```

If we were to query this in GraphQL, we would want the `id` and `name` fields to be populated from the database, but the database can't answer the name of our current process so that needs to be executed in memory. Also, even if we tried to pass that expression to Entity Framework it would throw an exception saying it doesn't know how to translate that to SQL.

A more realistic example for using this first goal is to implement schema introspection (#8). As part of setting up a type we could automatically add introspection fields, like so:

```
schema.GetType<User>()
    .AddField("__typename", () => schema.GetType<User>().Name)
```

The second goal of post-resolved fields is to operate on the data returned from the database using a function that can only execute in memory. The API I've settled for here is something like this:

```
schema.GetType<User>()
    .AddField("userAndProcessName",
        u => new {name = u.Name},
        args => $"User: {args.name}, Process: {Process.GetCurrentProcess().ProcessName}");
```

The mysterious anonymous type in the middle is so that we can define the required data for the function. In this case, the database would return the Name field, then that would be used to call the function with that data in memory. Ultimately, I think this second option is less important then the first (since it's not required for inspection) but I see it being really useful in certain scenarios.

**Comment by PeteDuncanson** [comment]
OK so you'd run through all the AddFields first via the DB then run the AddPostFields afterwards and do any additional processing. 

My mind jumps to the idea of possibly needing a PreField too? For instance what if you wanted to pull something from Session (ala the "me" alias in all the examples to get the current user) and then use that to look up additional info from the database?

**Comment by ckimes89** [comment]
PreField is an interesting idea, and I don't think I have a good way of implementing that right now. Something that strikes me though is that while a PostField only makes sense as a field, something like PreField could also exist as PreQuery. That is, the field "me" could exist either as a field on a type or as a query on the schema.

I'm thinking we could overload the concept of args to support this. I'll need to think through the API some more, but here's the first thing I came up with:

Using this overload of AddField (or the similar one for AddQuery):
https://github.com/ckimes89/graphql-net/blob/b24037f0e053bfb5886ebabce9e9a78b41cf5b60/GraphQL.Net/GraphQLTypeBuilder.cs#L21

Which looks something like this in practice:
https://github.com/ckimes89/graphql-net/blob/b24037f0e053bfb5886ebabce9e9a78b41cf5b60/Tests/InMemoryExecutionTests.cs#L42

We could add another overload that has a function to build the arguments, so something like:
```
schema.AddQuery("me",
    new { userId = 0 },  // define shape of arguments
    (db, args) => db.Users.Where(u => u.Id == args.userId).FirstOrDefault(), // define query
    () => new { userId = GetCurrentUser().Id }); // Func<TArgs> to execute for args
```

Of course, now that I think about it, you don't really need to define the argument shape the first time since it's defined in the function. So, that could probably be reduced to:

```
schema.AddQuery("me",
    () => new { userId = GetCurrentUser().Id }, // Func<TArgs> to execute for args
    (db, args) => db.Users.Where(u => u.Id == args.userId).FirstOrDefault(), // define query
```

This would let you do any pre-processing you need to do in order to build an arguments object. That args object would then be passed to the query.
