### ISSUE TITLE
The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by hernandezEsteban** [ckimes89/graphql-net#70]
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'GraphQL.Net.InteropHelpers.OrDefault<T>(Microsoft.FSharp.Core.FSharpOption<T>)' and 'GraphQL.Net.InteropHelpers.OrDefault<T>(Microsoft.FSharp.Core.FSharpOption<T>)'	GraphQL.Net	C:\Users\9zllklkjflkjfljkfdsk\Desktop\graphql-net-master\GraphQL.Net\GraphQLSchema.cs	219	Active
`
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'GraphQL.Net.StringExtensions.ToCamelCase(string)' and 'GraphQL.Net.StringExtensions.ToCamelCase(string)'	GraphQL.Net	C:\Users\9zllklkjflkjfljkfdsk\Desktop\graphql-net-master\GraphQL.Net\GraphQLTypeBuilder.cs	89	Active
`

**Comment by ckimes89** [comment]
Are you attempting to build the library from source? What version of Visual Studio?

This looks like a reference bug - like maybe a built version of the library is sitting in `obj` or `bin` and being referenced? That could lead to this sort of ambiguity error.

Try deleting your `bin` and `obj` folders, clean the solution, then rebuild.
