### ISSUE TITLE
FileLoadException FParsec-Pipes

### ISSUE THREAD

**Issue by muratoner** [ckimes89/graphql-net#71]
**Exception**

`İşlenmeyen Özel Durum: System.TypeInitializationException: '<StartupCode$GraphQL-Parser>.$GraphQL.Parser.Parser' tür başlatıcısı özel durum döndürdü. ---> System.IO.FileLoadException: 'FParsec-Pipes, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null' dosyasını veya derlemesini ya da bağımlılıklarından birini yükleyemedi. Tanımlayıcı adlı derleme gerekli. (HRESULT özel durum döndürdü: 0x80131044)
   konum: <StartupCode$GraphQL-Parser>.$GraphQL.Parser.Parser..cctor()
   --- İç özel durum yığını izlemesinin sonu ---
   konum: GraphQL.Parser.Parser.get_document()
   konum: GraphQL.Parser.Parser.parseDocument(String source)
   konum: GraphQL.Parser.GraphQLDocument`1.Parse(ISchema`1 schema, String source)
   konum: GraphQL.Net.GraphQL`1.ExecuteQuery(String queryStr, TContext queryContext)
   konum: GraphQL.Net.GraphQL`1.ExecuteQuery(String queryStr)
   konum: GraphQL.Net.Program.Main(String[] args) C:\Users\muhac\Documents\Visual Studio 2015\Projects\GraphQL.Net\GraphQL.Net\Program.cs içinde: satır 36`

Plaese help for this exception.

**Comment by ckimes89** [comment]
Apologies for the delay. Please try upgrading to version 0.3.3 through NuGet to see if it solves this issue.

**Comment by kellermanrivero** [comment]
The nuget definition references 0.1.1 version of FParsec-Pipes library, but the package references 0.3.1. The temporal workaround is to update manually FParsec-Pïpes library to the most recent version (0.3.1).

**Comment by ckimes89** [comment]
@kellermanrivero Oh of course, I forgot to update that when I upgraded FParsec-Pipes. Good catch!

I released version 0.3.4 which should reference the correct version of FParsec-Pipes in the nuget package.

**Comment by MarianPalkus** [comment]
@muratoner Can we close this issue?

**Comment by muratoner** [comment]
Yes please @MarianPalkus
