### ISSUE TITLE
EF issue - user is a value type and cannot be selected from

### ISSUE THREAD

**Issue by ronnpang1** [ckimes89/graphql-net#92]
Hi, all
I'm having a bit of an issue with graphql. I'm trying to query my dataset but im running into problems the moment  I try execute a query. I get the exeception: 

GraphQL.Parser.SourceException: 'field ``user'' is a value type and cannot be selected from'

My code is as follows:

```
   public void test() {
         var schema = GraphQL<AdtDbContext>.CreateDefaultSchema(() => new AdtDbContext());
         schema.AddType<NTC_TC_MAINS>().AddAllFields();            
         var gql = new GraphQL<AdtDbContext>(schema);
         schema.AddField("user", new { NAME = "-1" }, (db, args) => db.NTC_TC_MAINS.SingleOrDefault(u => u.TC_NAME == args.NAME));
         schema.Complete();
         var qresult = gql.ExecuteQuery("{user(NAME:\"Hudson\") {tC_NAME}}");
         Console.WriteLine(JsonConvert.SerializeObject(qresult, Formatting.Indented));
        }
```

With the following DBset:
`        public DbSet<NTC_TC_MAINS> NTC_TC_MAINS { get; set; }
`

![typeselectedfrom](https://user-images.githubusercontent.com/4573812/37929734-c357d342-310e-11e8-8690-c8f3701c5238.PNG)

The exception is as follows is as follows:
GraphQL.Parser.SourceException occurred
  HResult=0x80131500
  Message=field ``user'' is a value type and cannot be selected from
  Source=GraphQL.Parser
  StackTrace:
<Cannot evaluate the exception stack trace>

Any advice into solving this would be greatly helpful!

**Comment by ckimes89** [comment]
What's the query you're running? Is `NTC_TC_MAINS` a class or a struct?

**Comment by ronnpang1** [comment]
Thanks for Replying!
NTC_TC_MAINS is a class as is defined as follows:
```
namespace ATD.Domain.Entities
{
    [Table("NTC_TC_MAINS")]
    public class NTC_TC_MAINS
    {
        [Key]
        [MaxLength(100)]
        public string ID { get; set; }
        [Required]
        [MaxLength(1000)]
        public string TC_NAME { get; set; }
        [Required]
        public int TC_TYPE_ID { get; set; }
        [Required]
        public int TC_SUB_TYPE_ID { get; set; }
        [Required]
        public int TC_CERT_TYPE_ID { get; set; }
        [MaxLength(200)]
        public string TC_CERT_DOC { get; set; }
        [MaxLength(200)]
        public string TC_LOGO { get; set; }
        [MaxLength(4000)]
        public string TC_VISION { get; set; }
        [MaxLength(4000)]
        public string TC_DESC { get; set; }
        [Required]
        public int TC_AFFI_ID { get; set; }
     }
}
```
The main query im trying to run is to find any NTC_TC_MAIN with the name "Hudson".


```
    {
     user(NAME:\"Hudson\") 
      {
        tC_NAME,tC_LOGO,tC_VISION
      }
    }
```



  I was running into a similar issue as #49, where I inherited a database with names that are all uppercased.

I don't know if it helps but everything works fine the moment I I grab a list and instantiate a new context like so, it works:

```
        class Context
        {
            public IList<NTC_TC_MAINS> ntc { get; set; }
        }

        public void test()
        {
            List<NTC_TC_MAINS> allTCs = null;
            using (AtduDbContext context = new AtduDbContext())
            {
                allTCs = context.NTC_TC_MAINS.Select(t => (t)).ToList();

                var schema = GraphQL<Context>.CreateDefaultSchema(() =>
                    new Context
                    {
                        ntc = allTCs
                    });
                schema.AddType<NTC_TC_MAINS>().AddAllFields();
                schema.AddField("user", new { NAME = "-1" }, (C, args) => C.ntc.SingleOrDefault(u => u.TC_NAME == args.NAME));
                schema.Complete();
                var gql = new GraphQL<Context>(schema);
                var qresult = gql.ExecuteQuery("{user(NAME:\"Hudson\") {tC_NAME,tC_LOGO,tC_VISION}}");
                System.Diagnostics.Debug.Write("graphsqlul" + (JsonConvert.SerializeObject(qresult, Formatting.Indented)));
            }
```
But I don't want to call and grab the entire list all the time. Would rather be able to run the graphQL query and filter based on that.

**Comment by ckimes89** [comment]
Can you try using FirstOrDefault?

**Comment by ronnpang1** [comment]
changed to:
`            schema.AddField("user", new { id = "-1" }, (db, args) => db.NTC_TC_MAINS.Where(u => u.TC_NAME == args.id).FirstOrDefault());
`
Still gives me the same exception though

**Comment by ckimes89** [comment]
`AddField` should return a `GraphQLFieldBuilder`. Can you assign that to a
variable and inspect the private fields in the debugger (expand the _field
field and its Type property), then paste the results here?

**Comment by ckimes89** [comment]
So the immediate issue is that type.IsScalar is true, which is definitely
not correct. I'll have to think some on why that could be.

Is it possible that `NTC_TC_MAINS` is defined twice in your project, and
that the one used in `schema.AddType<NTC_TC_MAINS>().AddAllFields();` is
not the same as the one used in `db.NTC_TC_MAINS`?

**Comment by ronnpang1** [comment]
Oh man, you were absolutely right, NTC_MAIN was defined twice accidentally.
Everything works now, thank you so much!
